### ISSUE TITLE
problem installing dataset as sqlite

### ISSUE THREAD

**Issue by emchristensen** [ropensci/ecoretriever#78]
get an error when trying to run command "retriever install sqlite wine-quality" (same problem with wood-density too)
installing as csv, json, or xml works fine
running on windows 10, using python 2.7

Error message:
Traceback (most recent call last):
File "C:\Users\EC\Anaconda\Scripts\retriever-script.py", line 9, in 
load_entry_point('retriever==2.0.dev0', 'console_scripts', 'retriever')()
File "c:\users\ec\anaconda\lib\site-packages\retriever_main_.py", line 175, in main
dataset.download(engine, debug=debug)
File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\templates.py", line 102, in download
self.engine.insert_data_from_url(value)
File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 632, in insert_data_from_url
self.insert_data_from_file(find)
File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 624, in insert_data_from_file
self.add_to_table(data_source)
File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 116, in add_to_table
self.execute(insert_stmt, commit=False)
File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 480, in execute
self.cursor.execute(statement)
sqlite3.OperationalError: near ",": syntax error

**Comment by ethanwhite** [comment]
Thanks @emchristensen - I'm going to close this one since it's an issue with the core Data Retriever. Thanks for reporting it over there.
